"""外贸风险极端博弈样本生成器。"""

from __future__ import annotations

from pathlib import Path
import json
from typing import Any


AGENT_ROLES = [
    {
        "agent_id": "counterparty_radar",
        "agent_name": "CounterpartyRadarAgent",
        "focus": "counterparty_payment",
    },
    {
        "agent_id": "compliance_sentinel",
        "agent_name": "ComplianceSentinelAgent",
        "focus": "compliance_sanctions",
    },
    {
        "agent_id": "fulfillment_pulse",
        "agent_name": "FulfillmentPulseAgent",
        "focus": "fulfillment_margin",
    },
]

COUNTRIES = {
    "low": ["Germany", "Netherlands", "Japan", "Canada", "Australia"],
    "elevated": ["Nigeria", "Kazakhstan", "United Arab Emirates", "Turkey"],
    "high": ["Russia", "Iran", "Belarus", "Syria"],
}

TRANSIT = [None, "Turkey", "Georgia", "United Arab Emirates", "Armenia"]
PRODUCTS = [
    ("工业通信模组", "electronics"),
    ("高精度伺服控制模组", "dual_use"),
    ("包装机械备件", "machinery"),
    ("自动化装配夹具", "machinery"),
    ("小家电组合套装", "consumer_goods"),
]


def _sample(
    *,
    sample_id: str,
    scenario_name: str,
    counterparty_name: str,
    destination_country: str,
    product_name: str,
    product_category: str,
    trade_value_usd: float,
    payment_method: str,
    payment_days: int,
    deposit_ratio: float,
    incoterm: str,
    requested_discount_ratio: float,
    account_age_days: int,
    uses_free_email: bool,
    asks_undervalue_invoice: bool,
    asks_split_payment_to_third_party: bool,
    asks_release_bl_before_payment: bool,
    hs_code_sensitive: bool,
    sanction_watch_hit: bool,
    transshipment_country: str | None,
    documents_complete_ratio: float,
    kyc_verified: bool,
    export_license_ready: bool,
    production_buffer_days: int,
    logistics_delay_days: int,
    gross_margin_ratio: float,
    inventory_ready_ratio: float,
    prior_dispute_count: int,
    source_reputation: float,
    notes: list[str],
) -> dict[str, Any]:
    return {
        "sample_id": sample_id,
        "scenario_name": scenario_name,
        "counterparty_name": counterparty_name,
        "destination_country": destination_country,
        "product_name": product_name,
        "product_category": product_category,
        "trade_value_usd": trade_value_usd,
        "payment_method": payment_method,
        "payment_days": payment_days,
        "deposit_ratio": deposit_ratio,
        "incoterm": incoterm,
        "requested_discount_ratio": requested_discount_ratio,
        "account_age_days": account_age_days,
        "uses_free_email": uses_free_email,
        "asks_undervalue_invoice": asks_undervalue_invoice,
        "asks_split_payment_to_third_party": asks_split_payment_to_third_party,
        "asks_release_bl_before_payment": asks_release_bl_before_payment,
        "hs_code_sensitive": hs_code_sensitive,
        "sanction_watch_hit": sanction_watch_hit,
        "transshipment_country": transshipment_country,
        "documents_complete_ratio": documents_complete_ratio,
        "kyc_verified": kyc_verified,
        "export_license_ready": export_license_ready,
        "production_buffer_days": production_buffer_days,
        "logistics_delay_days": logistics_delay_days,
        "gross_margin_ratio": gross_margin_ratio,
        "inventory_ready_ratio": inventory_ready_ratio,
        "prior_dispute_count": prior_dispute_count,
        "source_reputation": source_reputation,
        "notes": notes,
    }


def _build_sanction_override_family() -> list[dict[str, Any]]:
    specs = [
        ("俄罗斯老客：合规名单命中", "Russia", True, False, False, "Turkey"),
        ("伊朗老客：低报发票施压", "Iran", True, True, False, "United Arab Emirates"),
        ("白俄罗斯老客：双用途补单", "Belarus", True, False, True, "Armenia"),
        ("叙利亚代理：终端用途模糊", "Syria", True, False, True, "Turkey"),
        (
            "阿联酋老客：转口链路异常",
            "United Arab Emirates",
            True,
            False,
            True,
            "Turkey",
        ),
        ("土耳其分销商：许可证缺口", "Turkey", False, False, True, "Georgia"),
        ("哈萨克斯坦老客：灰色转口试探", "Kazakhstan", False, False, True, "Georgia"),
        (
            "阿联酋老客：双用途保税转仓",
            "United Arab Emirates",
            True,
            False,
            True,
            "Turkey",
        ),
        ("俄罗斯分销商：单证完整但名单命中", "Russia", True, False, False, None),
        (
            "土耳其代理：低报 + 敏感品类",
            "Turkey",
            False,
            True,
            True,
            "United Arab Emirates",
        ),
    ]
    samples: list[dict[str, Any]] = []
    for index, spec in enumerate(specs, start=1):
        scenario, destination, sanction_hit, undervalue, license_gap, transit = spec
        product_name, product_category = PRODUCTS[1]
        samples.append(
            _sample(
                sample_id=f"stress-sanction-{index:03d}",
                scenario_name=scenario,
                counterparty_name=f"Legacy Compliance Buyer {index}",
                destination_country=destination,
                product_name=product_name,
                product_category=product_category,
                trade_value_usd=185000 + index * 9000,
                payment_method="insured_lc",
                payment_days=20,
                deposit_ratio=0.4,
                incoterm="CIF",
                requested_discount_ratio=0.03,
                account_age_days=1500 + index * 30,
                uses_free_email=False,
                asks_undervalue_invoice=undervalue,
                asks_split_payment_to_third_party=False,
                asks_release_bl_before_payment=False,
                hs_code_sensitive=True,
                sanction_watch_hit=sanction_hit,
                transshipment_country=transit,
                documents_complete_ratio=0.92,
                kyc_verified=True,
                export_license_ready=not license_gap,
                production_buffer_days=18,
                logistics_delay_days=3 + index % 5,
                gross_margin_ratio=0.24,
                inventory_ready_ratio=0.92,
                prior_dispute_count=0,
                source_reputation=0.9,
                notes=[
                    "matrix_family=sanction_override",
                    "conflict_vector=old_customer_vs_compliance_veto",
                    "target_behavior=一票否决覆盖信用与履约优势",
                ],
            )
        )
    return samples


def _build_boundary_blur_family() -> list[dict[str, Any]]:
    specs = [
        (
            "尼日利亚边界模糊：三维中风险叠加",
            "Nigeria",
            False,
            True,
            True,
            0.26,
            45,
            8,
            9,
            0.14,
            0.76,
        ),
        (
            "哈萨克斯坦边界模糊：敏感编码但无制裁",
            "Kazakhstan",
            False,
            True,
            True,
            0.24,
            45,
            8,
            10,
            0.14,
            0.72,
        ),
        (
            "阿联酋边界模糊：双用途但许可齐备",
            "United Arab Emirates",
            True,
            True,
            False,
            0.26,
            45,
            8,
            9,
            0.15,
            0.78,
        ),
        (
            "土耳其边界模糊：交付与合规同时冒尖",
            "Turkey",
            True,
            True,
            False,
            0.25,
            45,
            7,
            10,
            0.13,
            0.7,
        ),
        (
            "尼日利亚边界模糊：KYC 缺口但无阻断项",
            "Nigeria",
            False,
            True,
            True,
            0.28,
            45,
            9,
            8,
            0.14,
            0.74,
        ),
        (
            "哈萨克斯坦边界模糊：双用途边缘交易",
            "Kazakhstan",
            True,
            True,
            False,
            0.27,
            30,
            8,
            9,
            0.15,
            0.76,
        ),
        (
            "阿联酋边界模糊：单证缺口推高观察级",
            "United Arab Emirates",
            False,
            False,
            False,
            0.26,
            45,
            8,
            8,
            0.14,
            0.76,
        ),
        (
            "土耳其边界模糊：清关责任抬升履约压力",
            "Turkey",
            False,
            False,
            False,
            0.25,
            45,
            7,
            11,
            0.13,
            0.72,
        ),
        (
            "尼日利亚边界模糊：定价过激但未触发阻断",
            "Nigeria",
            False,
            False,
            False,
            0.24,
            45,
            8,
            9,
            0.14,
            0.75,
        ),
        (
            "哈萨克斯坦边界模糊：链路可信度下降",
            "Kazakhstan",
            False,
            True,
            False,
            0.25,
            45,
            9,
            8,
            0.15,
            0.77,
        ),
    ]
    samples: list[dict[str, Any]] = []
    for index, spec in enumerate(specs, start=1):
        (
            scenario,
            destination,
            dual_use,
            hs_sensitive,
            license_gap,
            deposit_ratio,
            payment_days,
            production_buffer,
            logistics_delay,
            margin,
            inventory_ratio,
        ) = spec
        product_name, default_category = PRODUCTS[index % len(PRODUCTS)]
        samples.append(
            _sample(
                sample_id=f"stress-boundary-{index:03d}",
                scenario_name=scenario,
                counterparty_name=f"Boundary Drift Trading {index}",
                destination_country=destination,
                product_name=product_name,
                product_category="dual_use" if dual_use else default_category,
                trade_value_usd=118000 + index * 6000,
                payment_method="tt_30_70",
                payment_days=payment_days,
                deposit_ratio=deposit_ratio,
                incoterm="DAP" if index % 2 else "DDP",
                requested_discount_ratio=0.09 if index in {1, 5, 9} else 0.07,
                account_age_days=120 + index * 12,
                uses_free_email=False,
                asks_undervalue_invoice=False,
                asks_split_payment_to_third_party=False,
                asks_release_bl_before_payment=False,
                hs_code_sensitive=hs_sensitive,
                sanction_watch_hit=False,
                transshipment_country=TRANSIT[(index % 4) + 1],
                documents_complete_ratio=0.74 if index % 3 else 0.79,
                kyc_verified=index not in {5},
                export_license_ready=not license_gap,
                production_buffer_days=production_buffer,
                logistics_delay_days=logistics_delay,
                gross_margin_ratio=margin,
                inventory_ready_ratio=inventory_ratio,
                prior_dispute_count=1 if index in {2, 4, 8} else 0,
                source_reputation=0.57 if index % 2 else 0.61,
                notes=[
                    "matrix_family=boundary_blur",
                    "conflict_vector=multi_medium_accumulation",
                    "target_behavior=验证 observe 与 gated_continue 边界",
                ],
            )
        )
    return samples


def _build_counterparty_deception_family() -> list[dict[str, Any]]:
    specs = [
        ("企业邮箱壳公司：第三方保理收款", False, True, False, 0.18, 60, True),
        ("新注册主体：先放单后付尾款", False, False, True, 0.2, 45, False),
        ("老站新壳：账期拉长并压价", True, False, False, 0.18, 75, False),
        ("看似正规分销商：第三方收款链路", True, True, False, 0.22, 60, False),
        ("保理包装交易：受益人核验缺失", True, False, False, 0.2, 60, False),
        ("空壳公司：免费邮箱切企业签名", False, False, False, 0.15, 75, True),
        ("同名不同账户：历史争议重现", True, True, False, 0.18, 60, False),
        ("代理商代采：要求先排产后补 KYC", False, False, False, 0.15, 60, False),
        ("企业邮箱壳公司：提单控制权松动", True, False, True, 0.22, 45, False),
        ("空壳贸易商：长账期 + 低首付", False, False, False, 0.12, 90, False),
    ]
    samples: list[dict[str, Any]] = []
    for index, spec in enumerate(specs, start=1):
        (
            scenario,
            mature_shell,
            third_party,
            release_bl,
            deposit_ratio,
            payment_days,
            free_email,
        ) = spec
        product_name, product_category = PRODUCTS[0]
        account_age_days = 420 if mature_shell else 45 + index * 8
        samples.append(
            _sample(
                sample_id=f"stress-counterparty-{index:03d}",
                scenario_name=scenario,
                counterparty_name=f"Opaque Route Holdings {index}",
                destination_country=COUNTRIES["elevated"][
                    index % len(COUNTRIES["elevated"])
                ],
                product_name=product_name,
                product_category=product_category,
                trade_value_usd=98000 + index * 7000,
                payment_method="open_account" if index % 2 else "tt_after_bl",
                payment_days=payment_days,
                deposit_ratio=deposit_ratio,
                incoterm="FOB",
                requested_discount_ratio=0.11 if index % 3 else 0.06,
                account_age_days=account_age_days,
                uses_free_email=free_email,
                asks_undervalue_invoice=False,
                asks_split_payment_to_third_party=third_party,
                asks_release_bl_before_payment=release_bl,
                hs_code_sensitive=False,
                sanction_watch_hit=False,
                transshipment_country=None,
                documents_complete_ratio=0.58 if index % 2 else 0.66,
                kyc_verified=False,
                export_license_ready=True,
                production_buffer_days=12,
                logistics_delay_days=5,
                gross_margin_ratio=0.17,
                inventory_ready_ratio=0.82,
                prior_dispute_count=2 if index in {4, 7} else 1,
                source_reputation=0.46 if not mature_shell else 0.65,
                notes=[
                    "matrix_family=counterparty_deception",
                    "conflict_vector=surface_legitimacy_vs_payment_pathology",
                    "target_behavior=验证对手方欺骗与支付术语脆弱点",
                ],
            )
        )
    return samples


def _build_fulfillment_crunch_family() -> list[dict[str, Any]]:
    specs = [
        ("优质客户：DDP 大单但产能锁死", 3, 16, 0.08, 0.35, 0.32, 180000),
        ("优质客户：利润被压到警戒线", 4, 12, 0.09, 0.38, 0.42, 172000),
        ("优质客户：物流窗口塌缩", 6, 18, 0.11, 0.4, 0.48, 165000),
        ("优质客户：库存与替代料同时告急", 5, 10, 0.1, 0.38, 0.35, 158000),
        ("优质客户：高毛利幻想但排产失控", 2, 14, 0.12, 0.4, 0.45, 190000),
        ("优质客户：稳定付款却交付连锁抖动", 4, 9, 0.11, 0.35, 0.44, 152000),
        ("优质客户：海外到门责任放大", 3, 11, 0.09, 0.36, 0.38, 162000),
        ("优质客户：长链路海运积压", 5, 15, 0.1, 0.34, 0.49, 155000),
        ("优质客户：关键料晚到 + 薄利", 4, 12, 0.08, 0.37, 0.41, 148000),
        ("优质客户：旺季插单挤兑产能", 2, 8, 0.09, 0.35, 0.46, 175000),
    ]
    samples: list[dict[str, Any]] = []
    for index, spec in enumerate(specs, start=1):
        (
            scenario,
            production_buffer,
            logistics_delay,
            margin,
            deposit_ratio,
            inventory_ratio,
            trade_value,
        ) = spec
        product_name, product_category = PRODUCTS[3 if index % 2 else 4]
        samples.append(
            _sample(
                sample_id=f"stress-fulfillment-{index:03d}",
                scenario_name=scenario,
                counterparty_name=f"Trusted Operations Buyer {index}",
                destination_country=COUNTRIES["low"][index % len(COUNTRIES["low"])],
                product_name=product_name,
                product_category=product_category,
                trade_value_usd=trade_value,
                payment_method="insured_lc",
                payment_days=15,
                deposit_ratio=deposit_ratio,
                incoterm="DDP" if index % 2 else "DAP",
                requested_discount_ratio=0.03,
                account_age_days=1250 + index * 30,
                uses_free_email=False,
                asks_undervalue_invoice=False,
                asks_split_payment_to_third_party=False,
                asks_release_bl_before_payment=False,
                hs_code_sensitive=False,
                sanction_watch_hit=False,
                transshipment_country=None,
                documents_complete_ratio=0.97,
                kyc_verified=True,
                export_license_ready=True,
                production_buffer_days=production_buffer,
                logistics_delay_days=logistics_delay,
                gross_margin_ratio=margin,
                inventory_ready_ratio=inventory_ratio,
                prior_dispute_count=1 if index in {4, 8} else 0,
                source_reputation=0.91,
                notes=[
                    "matrix_family=fulfillment_crunch",
                    "conflict_vector=single_domain_dominance",
                    "target_behavior=验证高履约风险不会轻易误杀优质客户",
                ],
            )
        )
    return samples


def _build_control_band_family() -> list[dict[str, Any]]:
    specs = [
        ("标杆样本：稳定老客", "pass", 0.35, 20, 18, 4, 0.24, 0.95),
        ("标杆样本：单一轻微物流扰动", "pass", 0.35, 20, 16, 7, 0.23, 0.9),
        ("标杆样本：轻度观察级边缘", "observe", 0.28, 30, 9, 8, 0.16, 0.79),
        ("标杆样本：轻度库存波动", "observe", 0.3, 30, 10, 9, 0.16, 0.76),
        ("标杆样本：资料偏慢但仍可放行", "pass", 0.32, 30, 14, 5, 0.2, 0.88),
        ("标杆样本：低风险高金额", "pass", 0.35, 15, 15, 4, 0.22, 0.92),
        ("标杆样本：轻度定价压力", "observe", 0.29, 30, 12, 8, 0.17, 0.81),
        ("标杆样本：稳定客户轻度转口", "observe", 0.32, 30, 12, 7, 0.18, 0.82),
        ("标杆样本：KYC 已闭环", "pass", 0.35, 15, 16, 3, 0.23, 0.94),
        ("标杆样本：履约与单证均可控", "pass", 0.34, 20, 18, 4, 0.21, 0.93),
    ]
    samples: list[dict[str, Any]] = []
    for index, spec in enumerate(specs, start=1):
        (
            scenario,
            expected,
            deposit_ratio,
            payment_days,
            production_buffer,
            delay,
            margin,
            inventory_ratio,
        ) = spec
        product_name, product_category = PRODUCTS[index % len(PRODUCTS)]
        samples.append(
            _sample(
                sample_id=f"stress-control-{index:03d}",
                scenario_name=scenario,
                counterparty_name=f"Control Group Buyer {index}",
                destination_country=COUNTRIES["low"][index % len(COUNTRIES["low"])],
                product_name=product_name,
                product_category=product_category,
                trade_value_usd=90000 + index * 4000,
                payment_method="insured_lc",
                payment_days=payment_days,
                deposit_ratio=deposit_ratio,
                incoterm="FCA" if index % 2 else "FOB",
                requested_discount_ratio=0.05 if expected == "observe" else 0.03,
                account_age_days=900 + index * 35,
                uses_free_email=False,
                asks_undervalue_invoice=False,
                asks_split_payment_to_third_party=False,
                asks_release_bl_before_payment=False,
                hs_code_sensitive=False,
                sanction_watch_hit=False,
                transshipment_country="United Arab Emirates" if index == 8 else None,
                documents_complete_ratio=0.82 if expected == "observe" else 0.95,
                kyc_verified=True,
                export_license_ready=True,
                production_buffer_days=production_buffer,
                logistics_delay_days=delay,
                gross_margin_ratio=margin,
                inventory_ready_ratio=inventory_ratio,
                prior_dispute_count=0,
                source_reputation=0.88,
                notes=[
                    "matrix_family=control_band",
                    f"expected_disposition={expected}",
                    "target_behavior=验证系统不会持续误报",
                ],
            )
        )
    return samples


def _build_gated_corridor_family() -> list[dict[str, Any]]:
    specs = [
        {
            "scenario": "门控带：高信用压力 + 双用途许可缺口",
            "destination": "Kazakhstan",
            "payment_method": "tt_30_70",
            "payment_days": 45,
            "deposit_ratio": 0.24,
            "account_age_days": 180,
            "kyc_verified": False,
            "documents_complete_ratio": 0.75,
            "requested_discount_ratio": 0.09,
            "source_reputation": 0.63,
            "product_name": "高精度伺服控制模组",
            "product_category": "dual_use",
            "hs_code_sensitive": True,
            "export_license_ready": False,
            "transshipment_country": None,
            "incoterm": "DAP",
            "production_buffer_days": 8,
            "logistics_delay_days": 10,
            "gross_margin_ratio": 0.14,
            "inventory_ready_ratio": 0.74,
            "trade_value_usd": 168000,
            "prior_dispute_count": 0,
        },
        {
            "scenario": "门控带：老客户补单但边境合规抬升",
            "destination": "Turkey",
            "payment_method": "open_account",
            "payment_days": 45,
            "deposit_ratio": 0.24,
            "account_age_days": 180,
            "kyc_verified": False,
            "documents_complete_ratio": 0.68,
            "requested_discount_ratio": 0.09,
            "source_reputation": 0.63,
            "product_name": "工业通信模组",
            "product_category": "electronics",
            "hs_code_sensitive": True,
            "export_license_ready": False,
            "transshipment_country": None,
            "incoterm": "DDP",
            "production_buffer_days": 8,
            "logistics_delay_days": 10,
            "gross_margin_ratio": 0.14,
            "inventory_ready_ratio": 0.76,
            "trade_value_usd": 158000,
            "prior_dispute_count": 0,
        },
        {
            "scenario": "门控带：高账期但未越阻断线",
            "destination": "United Arab Emirates",
            "payment_method": "open_account",
            "payment_days": 59,
            "deposit_ratio": 0.24,
            "account_age_days": 260,
            "kyc_verified": False,
            "documents_complete_ratio": 0.78,
            "requested_discount_ratio": 0.09,
            "source_reputation": 0.61,
            "product_name": "工业通信模组",
            "product_category": "electronics",
            "hs_code_sensitive": True,
            "export_license_ready": False,
            "transshipment_country": "Turkey",
            "incoterm": "DAP",
            "production_buffer_days": 9,
            "logistics_delay_days": 9,
            "gross_margin_ratio": 0.14,
            "inventory_ready_ratio": 0.75,
            "trade_value_usd": 162000,
            "prior_dispute_count": 1,
        },
        {
            "scenario": "门控带：履约吃紧但资料勉强过线",
            "destination": "Nigeria",
            "payment_method": "tt_30_70",
            "payment_days": 45,
            "deposit_ratio": 0.26,
            "account_age_days": 220,
            "kyc_verified": True,
            "documents_complete_ratio": 0.79,
            "requested_discount_ratio": 0.07,
            "source_reputation": 0.59,
            "product_name": "包装机械备件",
            "product_category": "machinery",
            "hs_code_sensitive": True,
            "export_license_ready": False,
            "transshipment_country": None,
            "incoterm": "DDP",
            "production_buffer_days": 7,
            "logistics_delay_days": 12,
            "gross_margin_ratio": 0.13,
            "inventory_ready_ratio": 0.73,
            "trade_value_usd": 154000,
            "prior_dispute_count": 1,
        },
        {
            "scenario": "门控带：履约主导但信用仅中等承压",
            "destination": "Germany",
            "payment_method": "tt_30_70",
            "payment_days": 45,
            "deposit_ratio": 0.25,
            "account_age_days": 240,
            "kyc_verified": False,
            "documents_complete_ratio": 0.76,
            "requested_discount_ratio": 0.09,
            "source_reputation": 0.64,
            "product_name": "自动化装配夹具",
            "product_category": "machinery",
            "hs_code_sensitive": True,
            "export_license_ready": False,
            "transshipment_country": None,
            "incoterm": "DDP",
            "production_buffer_days": 8,
            "logistics_delay_days": 10,
            "gross_margin_ratio": 0.14,
            "inventory_ready_ratio": 0.75,
            "trade_value_usd": 168000,
            "prior_dispute_count": 2,
        },
        {
            "scenario": "门控带：履约主导且边境资料缺口并存",
            "destination": "Canada",
            "payment_method": "tt_30_70",
            "payment_days": 30,
            "deposit_ratio": 0.26,
            "account_age_days": 220,
            "kyc_verified": False,
            "documents_complete_ratio": 0.68,
            "requested_discount_ratio": 0.07,
            "source_reputation": 0.58,
            "product_name": "小家电组合套装",
            "product_category": "consumer_goods",
            "hs_code_sensitive": False,
            "export_license_ready": True,
            "transshipment_country": None,
            "incoterm": "DAP",
            "production_buffer_days": 8,
            "logistics_delay_days": 10,
            "gross_margin_ratio": 0.14,
            "inventory_ready_ratio": 0.74,
            "trade_value_usd": 166000,
            "prior_dispute_count": 2,
        },
        {
            "scenario": "门控带：信用主导且履约同步吃紧",
            "destination": "Japan",
            "payment_method": "open_account",
            "payment_days": 45,
            "deposit_ratio": 0.24,
            "account_age_days": 200,
            "kyc_verified": False,
            "documents_complete_ratio": 0.75,
            "requested_discount_ratio": 0.09,
            "source_reputation": 0.65,
            "product_name": "工业通信模组",
            "product_category": "electronics",
            "hs_code_sensitive": True,
            "export_license_ready": True,
            "transshipment_country": "Georgia",
            "incoterm": "DAP",
            "production_buffer_days": 8,
            "logistics_delay_days": 9,
            "gross_margin_ratio": 0.14,
            "inventory_ready_ratio": 0.75,
            "trade_value_usd": 170000,
            "prior_dispute_count": 1,
        },
        {
            "scenario": "门控带：高压价 + 敏感编码但无硬阻断",
            "destination": "Australia",
            "payment_method": "open_account",
            "payment_days": 45,
            "deposit_ratio": 0.25,
            "account_age_days": 210,
            "kyc_verified": False,
            "documents_complete_ratio": 0.75,
            "requested_discount_ratio": 0.11,
            "source_reputation": 0.65,
            "product_name": "工业通信模组",
            "product_category": "electronics",
            "hs_code_sensitive": True,
            "export_license_ready": False,
            "transshipment_country": None,
            "incoterm": "DAP",
            "production_buffer_days": 9,
            "logistics_delay_days": 9,
            "gross_margin_ratio": 0.14,
            "inventory_ready_ratio": 0.76,
            "trade_value_usd": 171000,
            "prior_dispute_count": 1,
        },
        {
            "scenario": "门控带：边缘双用途 + 中度争议历史",
            "destination": "Netherlands",
            "payment_method": "tt_30_70",
            "payment_days": 45,
            "deposit_ratio": 0.26,
            "account_age_days": 190,
            "kyc_verified": False,
            "documents_complete_ratio": 0.76,
            "requested_discount_ratio": 0.08,
            "source_reputation": 0.59,
            "product_name": "高精度伺服控制模组",
            "product_category": "dual_use",
            "hs_code_sensitive": True,
            "export_license_ready": False,
            "transshipment_country": None,
            "incoterm": "DDP",
            "production_buffer_days": 8,
            "logistics_delay_days": 10,
            "gross_margin_ratio": 0.14,
            "inventory_ready_ratio": 0.74,
            "trade_value_usd": 159000,
            "prior_dispute_count": 1,
        },
        {
            "scenario": "门控带：多维高压但均未触发一票否决",
            "destination": "Canada",
            "payment_method": "tt_30_70",
            "payment_days": 45,
            "deposit_ratio": 0.24,
            "account_age_days": 185,
            "kyc_verified": False,
            "documents_complete_ratio": 0.68,
            "requested_discount_ratio": 0.09,
            "source_reputation": 0.64,
            "product_name": "自动化装配夹具",
            "product_category": "machinery",
            "hs_code_sensitive": True,
            "export_license_ready": False,
            "transshipment_country": None,
            "incoterm": "DDP",
            "production_buffer_days": 8,
            "logistics_delay_days": 11,
            "gross_margin_ratio": 0.13,
            "inventory_ready_ratio": 0.74,
            "trade_value_usd": 173000,
            "prior_dispute_count": 2,
        },
    ]
    samples: list[dict[str, Any]] = []
    for index, spec in enumerate(specs, start=1):
        samples.append(
            _sample(
                sample_id=f"stress-gated-{index:03d}",
                scenario_name=spec["scenario"],
                counterparty_name=f"Gated Corridor Buyer {index}",
                destination_country=spec["destination"],
                product_name=spec["product_name"],
                product_category=spec["product_category"],
                trade_value_usd=spec["trade_value_usd"],
                payment_method=spec["payment_method"],
                payment_days=spec["payment_days"],
                deposit_ratio=spec["deposit_ratio"],
                incoterm=spec["incoterm"],
                requested_discount_ratio=spec["requested_discount_ratio"],
                account_age_days=spec["account_age_days"],
                uses_free_email=False,
                asks_undervalue_invoice=False,
                asks_split_payment_to_third_party=False,
                asks_release_bl_before_payment=False,
                hs_code_sensitive=spec["hs_code_sensitive"],
                sanction_watch_hit=False,
                transshipment_country=spec["transshipment_country"],
                documents_complete_ratio=spec["documents_complete_ratio"],
                kyc_verified=spec["kyc_verified"],
                export_license_ready=spec["export_license_ready"],
                production_buffer_days=spec["production_buffer_days"],
                logistics_delay_days=spec["logistics_delay_days"],
                gross_margin_ratio=spec["gross_margin_ratio"],
                inventory_ready_ratio=spec["inventory_ready_ratio"],
                prior_dispute_count=spec["prior_dispute_count"],
                source_reputation=spec["source_reputation"],
                notes=[
                    "matrix_family=gated_corridor",
                    "conflict_vector=high_conflict_non_blocking",
                    "target_behavior=拉宽 gated_continue 决策带",
                ],
            )
        )
    return samples


def generate_stress_sample_set() -> dict[str, Any]:
    """生成 60 条高冲突外贸风险样本。"""

    samples = [
        *_build_sanction_override_family(),
        *_build_boundary_blur_family(),
        *_build_counterparty_deception_family(),
        *_build_fulfillment_crunch_family(),
        *_build_control_band_family(),
        *_build_gated_corridor_family(),
    ]
    return {
        "sample_set_id": "foreign_trade_risk_stress_pack_v1",
        "cruise_goal": "对 3-Agent 裁决协议做 60 条极端博弈压测，覆盖合规一票否决、多维中风险叠加、对手方欺骗、单域履约挤兑、低风险对照组与高冲突非阻断门控带。",
        "agent_roles": AGENT_ROLES,
        "samples": samples,
    }


def export_stress_sample_set(path: str | Path) -> dict[str, Any]:
    """导出高冲突样本集。"""

    payload = generate_stress_sample_set()
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return payload
